version: 3

silent: true

vars:
  PROJECT_NAME: aws-rancher
  TERRAFORM_BINARY: terraform
  AWS_REGION: eu-west-2
  AWS_AZ: a

includes:
  cattle-prod:
    taskfile: ./Taskfile.defs.yaml
    vars:
      WORK_ENV: cattle-prod
      AWS_ACCOUNT_ID: 281287281094
      AWS_ACCOUNT_NAME: 'sarrionandia.co.uk'
      AWS_PROFILE: 'default'
      AWS_ROLE_ARN: 'arn:aws:iam::{{.AWS_ACCOUNT_ID}}:user/martin'
  cattle-b:
    taskfile: ./Taskfile.defs.yaml
    vars:
      WORK_ENV: cattle-b
      AWS_ACCOUNT_ID: 281287281094
      AWS_ACCOUNT_NAME: 'sarrionandia.co.uk'
      AWS_PROFILE: 'default'
      AWS_ROLE_ARN: 'arn:aws:iam::{{.AWS_ACCOUNT_ID}}:user/martin'

tasks:
  fmt:
    desc: Run Terraform fmt
    cmds:
      - '{{.TERRAFORM_BINARY}} fmt -diff -recursive'

  tflint:
    desc: Run TFLint
    cmds:
      - tflint --recursive

  tfsec:
    desc: Run TFSec
    cmds:
      - tfsec
