domain_name        = "sarrionandia.co.uk"
hostname           = "rancher-b3"
rancher_secret_arn = "arn:aws:secretsmanager:eu-west-2:281287281094:secret:rancher-QeIi1B"
instance_key_name  = "sarrionandia-eu-w2"
subnet_cidr        = "10.0.2.0/24"