apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "${cluster-issuer}"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${letsencrypt-email}"
    privateKeySecretRef:
      name: "${cluster-issuer}"
    solvers:
    - http01:
        ingress:
          class: traefik