apiVersion: helm.cattle.io/v1

kind: HelmChartConfig
metadata:
  name: traefik
  namespace: traefik
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        enabled: true
    logs:
      general:
        level: "${traefik-log-level}"
      access:
        enabled: "${traefik-access-log}"
    service:
      spec:
        externalTrafficPolicy: "${traefik-external-access-policy}"
    experimental:
      plugins:
        rewrite-body:
          moduleName: "github.com/packruler/rewrite-body"
          version: "v1.2.0"
        crowdsec-bouncer-traefik-plugin:
          moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
          version: "v1.3.5"