apiVersion: helm.cattle.io/v1

kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    logs:
      general:
        level: "${traefik-log-level}"
      access:
        enabled: "${traefik-access-log}"
    service:
      spec:
        externalTrafficPolicy: "${traefik-external-access-policy}"